#!/bin/bash

# Usage: Place target domains in /home/kali/recon/<org_name>/domains.txt

# Base Directory for root domains
baseDir="/home/kali/Recon"

if [[ -d "$baseDir" ]]; then
    for dir in "$baseDir"/*/; do
        if [[ -f "${dir}/domains.txt" ]]; then
            sector=$(basename "$dir")
            echo "Recon for $sector...."

            # Subdomain enumeration + resolution
            #subfinder -dL "${dir}/domains.txt" \
                #| alterx \
                #| dnsx \
                #| tee "${dir}/resolved_domains.txt"

            # DNS records
           # dnsx -l "${dir}/resolved_domains.txt" \
           #     -a -aaaa -cname -json -silent \
            #    > "${dir}/dns_records.json"

            # HTTPx (tech detection)
            #httpx -l "${dir}/resolved_domains.txt" \
                #-title -status-code -content-type -tech-detect -t 75 \
                #| tee "${dir}/httpx_techdetect.txt"

            # HTTPx probing (For Basic Output)
            #httpx -l "${dir}/resolved_domains.txt" \
                #| tee "${dir}/httpx_webservers.txt"

            # Crawling
            #katana -list "${dir}/httpx_webservers.txt" \
                #-jc -kf all \
                #-o "${dir}/katana.txt"

            # Port scanning
            #smap -iL "${dir}/resolved_domains.txt" \
                #| tee "${dir}/smap_openports.txt"

            # Historical URLs
            gau --threads 20 < "${dir}/resolved_domains.txt" \
                | tee "${dir}/gau.txt"

            waybackurls < "${dir}/resolved_domains.txt" \
                | tee "${dir}/wayback.txt"

            # Screenshots
            gowitness scan file \
                -f "${dir}/resolved_domains.txt" \
                --threads 50 \
                --write-db "${dir}/gowitness.db"


            # Nuclei DNS / takeover checks
            nuclei -l "${dir}/dns_records.json" \
                -tags dns,tech,takeover \
                -stats \
                | tee "${dir}/takeovers.txt"


        else
            echo "$(date): No root domains found for $(basename "$dir")!"
        fi
    done
else
    echo "$(date): Directory '$baseDir' does not exist."
fi

## Statistics
- **Total Resolved Domains:** $(wc -l < "${dir}/resolved_domains.txt" 2>/dev/null || echo "0")


# Start Gowitness Server at http://127.0.0.1:7171/
gowitness report server
